"""empty message

Revision ID: 71d4f5d4283b
Revises: cd8029d22e5c
Create Date: 2022-08-04 17:09:47.081047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71d4f5d4283b'
down_revision = 'cd8029d22e5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('address', sa.String(length=250), nullable=False))
    op.add_column('businesses', sa.Column('city', sa.String(length=100), nullable=False))
    op.add_column('businesses', sa.Column('state', sa.String(length=50), nullable=False))
    op.add_column('businesses', sa.Column('zipcode', sa.String(length=25), nullable=False))
    op.add_column('businesses', sa.Column('longitude', sa.Float(precision=25), nullable=False))
    op.add_column('businesses', sa.Column('latitude', sa.Float(precision=25), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('businesses', 'latitude')
    op.drop_column('businesses', 'longitude')
    op.drop_column('businesses', 'zipcode')
    op.drop_column('businesses', 'state')
    op.drop_column('businesses', 'city')
    op.drop_column('businesses', 'address')
    # ### end Alembic commands ###
